### PR TITLE
fix application list and get

### LINKED ISSUE #190: ocdev app should return current app, not create it if non existent
On a new cluster, new config, new install.

```
$ ocdev app list
ACTIVE   NAME

$ ocdev app
The current application is: app

$ ocdev app list
ACTIVE   NAME
  *      app
```

The command has created the app, and use it as default current app.

See #152

### PR DESCRIPTION
**Pull request by kadel**
This fixes bug where default application was created when listing apps or
just getting the current app.

- If `ocdev app` is run and there are no applications, a message is shown
  informing user about this fact. Previously it showed that default application is active.
- When `ocdev create ...` is run and there are no application, default
  the application is automatically created and used.

fixes #190 and #142 

TODO:
 - [x] fix tests

### CODE REVIEW

File: cmd/application.go [hunk 1]
```diff
@@ -58,9 +58,14 @@ var applicationGetCmd = &cobra.Command{
 		}
 		if applicationShortFlag {
 			fmt.Print(app)
-		} else {
-			fmt.Printf("The current application is: %v\n", app)
+			return
 		}
+		if app == "" {
+			fmt.Printf("There's no active application. You need to create one\n")
```
Comment (containscafeine) [inline cmd/application.go]: You can create one by running `ocdev application create <name>`

Comment (kadel) [reply cmd/application.go]: updated
